In [1]:
import torch
import torch.autograd as autograd
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

torch.manual_seed(1)

In [2]:
V_data = [1., 2., 3.,]
V = torch.tensor(V_data)
print(V)

tensor([1., 2., 3.])


In [5]:
M_data = [[1., 2., 2.,], [4., 5., 6]]
M = torch.tensor(M_data)
print(M)

tensor([[1., 2., 2.],
        [4., 5., 6.]])


In [7]:
T_data = [[[1.,2.,],[3.,4.,],
          [5.,5.],[7.,8.]]]
T = torch.tensor(T_data)
print(T, T.shape)

tensor([[[1., 2.],
         [3., 4.],
         [5., 5.],
         [7., 8.]]]) torch.Size([1, 4, 2])


In [13]:
print(V[0])
print(V[0].item())
print(M[0])
print(T[0])

tensor(1.)
1.0
tensor([1., 2., 2.])
tensor([[1., 2.],
        [3., 4.],
        [5., 5.],
        [7., 8.]])


In [15]:
x = torch.randn((3,4,5))
print(x)

tensor([[[ 0.4100,  0.4085,  0.2579,  1.0950, -0.5065],
         [ 0.0998, -0.6540,  0.7317, -1.4567,  1.6089],
         [ 0.0938, -1.2597,  0.2546, -0.5020, -1.0412],
         [ 0.7323,  1.3075, -1.1628,  0.1196, -0.1631]],

        [[ 0.6614,  1.1899,  0.8165, -0.9135, -0.3538],
         [ 0.7639, -0.5890, -0.7636,  1.3352,  0.6043],
         [-0.1034, -0.1512,  1.2466,  0.5057,  0.9505],
         [ 1.2966,  0.8738, -0.5603,  1.2858,  0.8168]],

        [[-1.4648, -1.2629,  1.1220,  1.5663, -1.0371],
         [-1.0669, -0.2085, -0.2155,  0.2705,  0.5597],
         [-0.3184,  1.5117, -1.5208,  0.9196, -0.5484],
         [-0.3472, -0.7474, -0.9234,  0.5734, -0.1093]]])


# 텐서로 작업하기

In [16]:
x = torch.tensor([1,2,3.])
y = torch.tensor([4.,5,6])
z = x + y
print(z)

tensor([5., 7., 9.])


In [17]:
x_1 = torch.randn(2, 5)
y_1 = torch.randn(3, 5)
z_1 = torch.cat([x_1, y_1])
print(z_1)

tensor([[-6.9328e-01, -1.6676e-01, -9.9988e-01, -1.6476e+00,  8.0983e-01],
        [ 5.5424e-02,  1.1340e+00, -5.3264e-01,  6.5921e-01, -1.5964e+00],
        [-3.7687e-01, -3.1020e+00, -9.9467e-02, -7.2126e-01,  1.2708e+00],
        [-2.0225e-03, -1.0952e+00,  6.0165e-01,  6.9841e-01, -8.0052e-01],
        [ 1.5381e+00,  1.4673e+00,  1.5951e+00, -1.5279e+00,  1.0156e+00]])


In [18]:
# 세로 연결:
x_2 = torch.randn(2, 3)
y_2 = torch.randn(2, 5)
# 두번째 변수는 연결될 축을 결정합니다.
z_2 = torch.cat([x_2, y_2], 1)
print(z_2)

tensor([[-0.2020, -1.2865,  0.8231,  0.6684,  1.1628, -0.3229,  1.8782, -0.5666],
        [-0.6101, -1.2960, -0.9434,  0.4016, -0.1153,  0.3170,  0.5629,  0.8662]])


In [19]:
x = torch.randn(2, 3, 4)
print(x)
print(x.view(2, 12))  # 가로 2 , 세로 12로 재구성
# 위와 같이 하나의 차원이 -1이면 그 것의 크기는 유추될 수 있습니다.
print(x.view(2, -1))

tensor([[[ 0.0127, -1.8734,  1.7997,  0.2824],
         [ 0.2151,  0.9385,  1.4657, -0.5565],
         [ 2.4142,  1.0206, -0.4405, -1.7342]],

        [[-1.0257,  0.5213, -0.4531, -0.1260],
         [-0.5882,  2.1189, -0.5422, -2.4593],
         [-0.9502, -0.3095,  1.6633,  0.5051]]])
tensor([[ 0.0127, -1.8734,  1.7997,  0.2824,  0.2151,  0.9385,  1.4657, -0.5565,
          2.4142,  1.0206, -0.4405, -1.7342],
        [-1.0257,  0.5213, -0.4531, -0.1260, -0.5882,  2.1189, -0.5422, -2.4593,
         -0.9502, -0.3095,  1.6633,  0.5051]])
tensor([[ 0.0127, -1.8734,  1.7997,  0.2824,  0.2151,  0.9385,  1.4657, -0.5565,
          2.4142,  1.0206, -0.4405, -1.7342],
        [-1.0257,  0.5213, -0.4531, -0.1260, -0.5882,  2.1189, -0.5422, -2.4593,
         -0.9502, -0.3095,  1.6633,  0.5051]])


In [21]:
x = torch.tensor([1.,2,3], requires_grad=True)
y = torch.tensor([4,5,6.], requires_grad=True)
z=x+y
print(z)
print(z.grad_fn)

tensor([5., 7., 9.], grad_fn=<AddBackward0>)


In [22]:
s = z.sum()
print(s)
print(s.grad_fn)

tensor(21., grad_fn=<SumBackward0>)


In [23]:
s.backward()
print(x.grad)

tensor([1., 1., 1.])


In [24]:
print(x.requires_grad)
print((x**2).requires_grad)

True
True


In [26]:
with torch.no_grad():
    print((x**2).requires_grad)

False
